version: '3'

services:
  db:
    container_name: database
    build: ./database
    ports: [5432:5432]
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    command: python manage.py runserver 0.0.0.0:8000
    
volumes:
  db: